# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish to AWS

on:
  push:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: cd web && npm ci
    - run: npm run build:web
    - name: Deploy GitHub Page
      uses: peaceiris/actions-gh-pages@v3.5.7
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web/build
    - run: npm run deploy
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.aws_secret_access_key}}
